// <auto-generated />
using BazaNieruchomosci.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BazaNieruchomosci.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190221141933_NewProperty")]
    partial class NewProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BazaNieruchomosci.Models.BuildingPlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area");

                    b.Property<string>("Description");

                    b.Property<string>("District");

                    b.Property<string>("Place");

                    b.Property<decimal>("Price");

                    b.Property<string>("Region");

                    b.Property<string>("SerialNumber");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.ToTable("BuildingPlots");
                });

            modelBuilder.Entity("BazaNieruchomosci.Models.CommercialSpace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area");

                    b.Property<string>("Description");

                    b.Property<string>("District");

                    b.Property<bool>("Parking");

                    b.Property<string>("Place");

                    b.Property<decimal>("Price");

                    b.Property<string>("SerialNumber");

                    b.Property<string>("Street");

                    b.Property<string>("Use");

                    b.Property<int>("YearOfBuilding");

                    b.HasKey("Id");

                    b.ToTable("CommercialSpaces");
                });

            modelBuilder.Entity("BazaNieruchomosci.Models.Flat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area");

                    b.Property<bool>("Balcony");

                    b.Property<string>("Description");

                    b.Property<string>("District");

                    b.Property<int>("Floor");

                    b.Property<bool>("Lift");

                    b.Property<string>("Place");

                    b.Property<decimal>("Price");

                    b.Property<int>("Rooms");

                    b.Property<string>("SerialNumber");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.ToTable("Flats");
                });

            modelBuilder.Entity("BazaNieruchomosci.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area");

                    b.Property<string>("Description");

                    b.Property<string>("District");

                    b.Property<int>("Floor");

                    b.Property<string>("Place");

                    b.Property<string>("PlotArea");

                    b.Property<decimal>("Price");

                    b.Property<int>("Rooms");

                    b.Property<string>("SerialNumber");

                    b.Property<string>("Street");

                    b.Property<int>("YearOfBuilding");

                    b.HasKey("Id");

                    b.ToTable("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
